# Project information
site_name: 'Touchviewer documentation'
site_description: 'Touchviewer documentation'
site_url: 'http://support-test.touchviewer.net/'



# Copyright
copyright: 'Copyright &copy; 2017 01 Project s.r.l.'

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'grey'
    accent: 'light blue'

extra_css:
  - 'stylesheets/extra.css'
# Extensions
markdown_extensions:
  - admonition
  - toc(permalink=false)
# Pages
pages:
  - Welcome: index.md
  - Italiano:
    - Overview: it/overview.md
    - Requisiti: it/requirements.md
    - Installazione: it/installation.md
    - Primo avvio: it/first-boot.md
    - Workspace: it/media-manager/workspace.md
    - Impostazioni: it/media-manager/settings.md
    - Contenuti:
      - Elenco Contenuti: it/media-manager/content-directory.md
      - Opzioni Cartella: it/media-manager/folder-option.md
      - Opzioni Contenuto: it/media-manager/content-option.md
      - Proprietà cartelle: it/media-manager/folder-properties.md
      - Proprietà contenuti: it/media-manager/content-properties.md
    - Theme Manager:
      - Panoramica: it/media-manager/themes/overview.md
      - Tema moduli: it/media-manager/themes/theme-module.md
      - Tema elementi: it/media-manager/themes/theme-element.md
      - Tema barra navigazione: it/media-manager/themes/theme-navigationbar.md
      - Tema barra anteprime: it/media-manager/themes/theme-previewbar.md
      - Tema del visualizzatore: it/media-manager/themes/theme-viewer.md
      - Tema popup strumenti: it/media-manager/themes/theme-toolspopup.md
    - Aggiungi Contenuti:
      - Panoramica : it/media-manager/contents/overview.md
      - Immagini : it/media-manager/contents/image.md
      - Video : it/media-manager/contents/video.md
      - PDF/Docs : it/media-manager/contents/pdf.md
      - Lista Immagini : it/media-manager/contents/image-list.md
      - Lista Video : it/media-manager/contents/video-list.md
      - Web Browser : it/media-manager/contents/web-browser.md
      - Ingresso Video : it/media-manager/contents/video-input.md
      - Streaming Video : it/media-manager/contents/video-streaming.md
    - Features:
      - Draw-On: it/media-manager/features/draw-on.md
      - Commenti: it/media-manager/features/comments.md
      - Info Points: it/media-manager/features/info-point.md
      - Ricerca: it/media-manager/features/search.md
      - Sincronizzazione: it/media-manager/features/network-sync.md
  - English:
    - Overview: en/overview.md
    - Requirements: en/requirements.md
    - Installation: en/installation.md
    - First Boot: en/first-boot.md
    - Workspace: en/media-manager/workspace.md
    - Settings: en/media-manager/settings.md
    - Contents:
      - Content List: en/media-manager/content-directory.md
      - Opzioni Cartella: en/media-manager/folder-option.md
      - Folder Options: en/media-manager/content-option.md
      - Folder Properties: en/media-manager/folder-properties.md
      - Content Properties: en/media-manager/content-properties.md
    - Theme Manager:
      - Themes Overview: en/media-manager/themes/overview.md
      - Modules Theme: en/media-manager/themes/theme-module.md
      - Elements Theme: en/media-manager/themes/theme-element.md
      - Navigation Bar Theme: en/media-manager/themes/theme-navigationbar.md
      - Preview Bar Theme: en/media-manager/themes/theme-previewbar.md
      - Viewer theme: en/media-manager/themes/theme-viewer.md
      - Tool Pop-up Theme: en/media-manager/themes/theme-toolspopup.md
    - Aggiungi Contenuti:
      - Overview : en/media-manager/contents/overview.md
      - Images : en/media-manager/contents/image.md
      - Video : en/media-manager/contents/video.md
      - PDF/Docs : en/media-manager/contents/pdf.md
      - Image List : en/media-manager/contents/image-list.md
      - Video List : en/media-manager/contents/video-list.md
      - Web Browser : en/media-manager/contents/web-browser.md
      - Video Input : en/media-manager/contents/video-input.md
      - Video Streaming : en/media-manager/contents/video-streaming.md
    - Features:
      - Draw-On: en/media-manager/features/draw-on.md
      - Comments: en/media-manager/features/comments.md
      - Info Points: en/media-manager/features/info-point.md
      - Search: en/media-manager/features/search.md
      - Synchronisation: en/media-manager/features/network-sync.md
